# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True)),
                ('humidity', models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True)),
                ('uv', models.IntegerField(default=None, null=True)),
                ('light', models.IntegerField(default=None, null=True)),
                ('rainfall', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
