# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('uv', models.IntegerField()),
                ('light', models.IntegerField()),
                ('rainfall', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
