# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('eng_name', models.CharField(max_length=50)),
                ('school_abbreviation', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
